/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login With Telegram */
        post: operations["login_with_telegram_api_v1_auth_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram/oidc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login With Telegram Oidc */
        post: operations["login_with_telegram_oidc_api_v1_auth_telegram_oidc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_api_v1_clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_api_v1_clients__client_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client Transactions */
        get: operations["get_client_transactions_api_v1_clients__client_id__transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Balances */
        get: operations["list_balances_api_v1_balances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/shadow-reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Shadow Report */
        get: operations["dashboard_shadow_report_api_v1_dashboard_shadow_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Rates */
        get: operations["dashboard_rates_api_v1_dashboard_rates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/manual-cash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_v1_dashboard_manual_cash_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/manual-cash/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record */
        post: operations["record_api_v1_dashboard_manual_cash_moves_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/manual-cash/moves/{move_id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reverse */
        post: operations["reverse_api_v1_dashboard_manual_cash_moves__move_id__reverse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deals */
        get: operations["list_deals_api_v1_deals_get"];
        put?: never;
        /** Create Deal */
        post: operations["create_deal_api_v1_deals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deals/{deal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deal */
        get: operations["get_deal_api_v1_deals__deal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Deal */
        patch: operations["update_deal_api_v1_deals__deal_id__patch"];
        trace?: never;
    };
    "/api/v1/deals/{deal_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Deal Status */
        post: operations["change_deal_status_api_v1_deals__deal_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settlements/{settlement_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Settlement Review */
        post: operations["resolve_settlement_review_api_v1_settlements__settlement_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deals/{deal_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Deal Source */
        patch: operations["edit_deal_source_api_v1_deals__deal_id__source_patch"];
        trace?: never;
    };
    "/api/v1/deals/{deal_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Deal Source */
        post: operations["cancel_deal_source_api_v1_deals__deal_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fulfillments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fulfillments */
        get: operations["list_fulfillments_api_v1_fulfillments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fulfillments/{item_id}/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder Fulfillment */
        post: operations["reorder_fulfillment_api_v1_fulfillments__item_id__reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fulfillments/{item_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Fulfillment */
        post: operations["cancel_fulfillment_api_v1_fulfillments__item_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiUser */
        ApiUser: {
            /** Id */
            id: number;
            /** Tg User Id */
            tg_user_id: number;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["UserRole"];
            /** Cities */
            cities?: string[];
            /** Is Active */
            is_active: boolean;
        };
        /** BalanceClientDto */
        BalanceClientDto: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Clientnumber */
            clientNumber: string;
            /** Currency */
            currency: string;
            /** Balance */
            balance: number;
            /** Balancerub */
            balanceRub: number;
            /** Initials */
            initials: string;
            /** Telegramchatid */
            telegramChatId?: string | null;
        };
        /** BalancesSnapshotResponse */
        BalancesSnapshotResponse: {
            /** Clients */
            clients: components["schemas"]["BalanceClientDto"][];
            /** Summaries */
            summaries: components["schemas"]["CurrencySummaryDto"][];
        };
        /** BestChangeDetailsDto */
        BestChangeDetailsDto: {
            /** Operation */
            operation: string;
            /** Qtyusdt */
            qtyUsdt?: number | null;
            /** Marketraterub */
            marketRateRub?: number | null;
            /** Clientraterub */
            clientRateRub?: number | null;
            /** Unitspreadrub */
            unitSpreadRub?: number | null;
            /** Grossspreadrub */
            grossSpreadRub?: number | null;
            /** Profitpoolrub */
            profitPoolRub?: number | null;
            /** Partnersharerub */
            partnerShareRub?: number | null;
            /** Skyexprofitrub */
            skyexProfitRub?: number | null;
            /** Platformfeeusdt */
            platformFeeUsdt?: number | null;
            /** Originaldealid */
            originalDealId?: string | null;
            /** Replacementdealid */
            replacementDealId?: string | null;
            /** Correctionreason */
            correctionReason?: string | null;
            /** Correctionactor */
            correctionActor?: string | null;
        };
        /** CashSourceEditRequest */
        CashSourceEditRequest: {
            /** City */
            city: string;
            /** Amount */
            amount?: number | string | null;
            /** Inamount */
            inAmount?: number | string | null;
            /** Outamount */
            outAmount?: number | string | null;
            /** Comment */
            comment?: string | null;
            /**
             * Contact1
             * @default
             */
            contact1: string;
            /**
             * Contact2
             * @default
             */
            contact2: string;
        };
        /** ClientBalanceDto */
        ClientBalanceDto: {
            /** Currency */
            currency: string;
            /** Amount */
            amount: number;
        };
        /** ClientCommentDto */
        ClientCommentDto: {
            /** Id */
            id: string;
            /** Date */
            date: string;
            /** Author */
            author: string;
            /** Text */
            text: string;
        };
        /** ClientDto */
        ClientDto: {
            /** Id */
            id: string;
            /** Clientnumber */
            clientNumber: string;
            /** Name */
            name: string;
            /** Initials */
            initials: string;
            /** Telegramusername */
            telegramUsername: string;
            /** Telegramchatid */
            telegramChatId: string;
            /** Dealscount */
            dealsCount: number;
            /** Turnoverrub */
            turnoverRub: number;
            /** Managername */
            managerName: string;
            /** Registrationdate */
            registrationDate: string;
            /** Counterpartyname */
            counterpartyName?: string | null;
            /** Counterpartypercent */
            counterpartyPercent?: number | null;
            /** Comment */
            comment?: string | null;
            /** Balances */
            balances?: components["schemas"]["ClientBalanceDto"][];
            /** Totalprofitrub */
            totalProfitRub: number;
            /** Purchasevolumerub */
            purchaseVolumeRub: number;
            /** Salevolumerub */
            saleVolumeRub: number;
            /** Averagecheckrub */
            averageCheckRub: number;
            /** Recentdeals */
            recentDeals?: components["schemas"]["ClientRecentDealDto"][];
            /** Comments */
            comments?: components["schemas"]["ClientCommentDto"][];
        };
        /** ClientMetricDto */
        ClientMetricDto: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Value */
            value: string | number;
            /** Changepercent */
            changePercent: number;
            /** Subtitle */
            subtitle: string;
            /** Tone */
            tone: string;
            /** Icon */
            icon: string;
        };
        /** ClientRecentDealDto */
        ClientRecentDealDto: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Direction */
            direction: string;
            /** Amountrub */
            amountRub: number;
            /** Time */
            time: string;
        };
        /** ClientTransactionDto */
        ClientTransactionDto: {
            /** Id */
            id: string;
            /** Txnat */
            txnAt: string;
            /** Currency */
            currency: string;
            /** Amount */
            amount: number;
            /** Balanceafter */
            balanceAfter: number;
            /** Comment */
            comment?: string | null;
            /** Source */
            source?: string | null;
            /** Groupname */
            groupName?: string | null;
            /** Actorname */
            actorName?: string | null;
        };
        /** ClientTransactionsResponse */
        ClientTransactionsResponse: {
            /** Items */
            items: components["schemas"]["ClientTransactionDto"][];
            /** Limit */
            limit: number;
        };
        /** ClientsPageResponse */
        ClientsPageResponse: {
            /** Metrics */
            metrics: components["schemas"]["ClientMetricDto"][];
            /** Clients */
            clients: components["schemas"]["ClientDto"][];
            /** Totalclients */
            totalClients: number;
        };
        /** CurrencySummaryDto */
        CurrencySummaryDto: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Changepercent */
            changePercent?: number | null;
            /** Tone */
            tone: string;
        };
        /** DashboardCitySummaryDto */
        DashboardCitySummaryDto: {
            /** Id */
            id: string;
            /** City */
            city: string;
            /** Rows */
            rows: components["schemas"]["DashboardCitySummaryRowDto"][];
        };
        /** DashboardCitySummaryRowDto */
        DashboardCitySummaryRowDto: {
            /** Label */
            label: string;
            /** Value */
            value: string | number;
            /** Tone */
            tone?: string | null;
        };
        /** DashboardCurrencyFactDto */
        DashboardCurrencyFactDto: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Amount */
            amount: string;
            /** Rate */
            rate: string;
            /** Rubvalue */
            rubValue: string;
            /** Clientamount */
            clientAmount: string;
            /** Dealprofitamount */
            dealProfitAmount: string;
            /** Factamount */
            factAmount: string;
            /** Observedamount */
            observedAmount: string | null;
            /** Gap */
            gap: string | null;
            /** Observedat */
            observedAt: string | null;
            /** Tone */
            tone: string;
        };
        /** DashboardDailyIndicatorDto */
        DashboardDailyIndicatorDto: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Value */
            value: string | number;
            /** Tone */
            tone: string;
        };
        /** DashboardFinanceIndicatorDto */
        DashboardFinanceIndicatorDto: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Value */
            value: string | number;
            /** Percent */
            percent?: string | null;
            /** Isnegative */
            isNegative?: boolean | null;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Source */
            source: string;
            /**
             * Calculatedat
             * Format: date-time
             */
            calculatedAt: string;
            /**
             * Dataasof
             * Format: date-time
             */
            dataAsOf: string;
            /** Warnings */
            warnings: string[];
            shadowComparison?: components["schemas"]["DashboardShadowComparisonDto"] | null;
            /** Datelabel */
            dateLabel: string;
            /** Weekdaylabel */
            weekdayLabel: string;
            /** Cities */
            cities: string[];
            /** Topmetrics */
            topMetrics: components["schemas"]["DashboardTopMetricDto"][];
            /** Dailyindicators */
            dailyIndicators: components["schemas"]["DashboardDailyIndicatorDto"][];
            /** Currencies */
            currencies: components["schemas"]["DashboardCurrencyFactDto"][];
            /** Finance */
            finance: components["schemas"]["DashboardFinanceIndicatorDto"][];
            /** Citysummaries */
            citySummaries: components["schemas"]["DashboardCitySummaryDto"][];
            /** Systemmetrics */
            systemMetrics: components["schemas"]["DashboardSystemMetricDto"][];
            /** Lastupdatedlabel */
            lastUpdatedLabel: string;
        };
        /** DashboardShadowComparisonDto */
        DashboardShadowComparisonDto: {
            /** Status */
            status: string;
            /** Comparedfields */
            comparedFields: number;
            /** Mismatchcount */
            mismatchCount: number;
            /** Reportid */
            reportId?: number | null;
        };
        /** DashboardShadowDifferenceDto */
        DashboardShadowDifferenceDto: {
            /** Path */
            path: string;
            /** Sheet */
            sheet: string | null;
            /** Database */
            database: string | null;
            /** Absolutedelta */
            absoluteDelta: string | null;
            /** Relativedelta */
            relativeDelta: string | null;
            /** Classification */
            classification: string;
        };
        /** DashboardShadowReportDto */
        DashboardShadowReportDto: {
            /** Id */
            id: number;
            /**
             * Businessdate
             * Format: date
             */
            businessDate: string;
            /** Primarysource */
            primarySource: string;
            /** Status */
            status: string;
            /** Comparedfields */
            comparedFields: number;
            /** Mismatchcount */
            mismatchCount: number;
            /** Absolutetolerance */
            absoluteTolerance: string;
            /** Relativetolerance */
            relativeTolerance: string;
            /**
             * Sheetsdataasof
             * Format: date-time
             */
            sheetsDataAsOf: string;
            /**
             * Dbdataasof
             * Format: date-time
             */
            dbDataAsOf: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Differences */
            differences: components["schemas"]["DashboardShadowDifferenceDto"][];
        };
        /** DashboardSystemMetricDto */
        DashboardSystemMetricDto: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Value */
            value: string | number;
            /** Subtitle */
            subtitle: string;
            /** Tone */
            tone: string;
        };
        /** DashboardTopMetricDto */
        DashboardTopMetricDto: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Value */
            value: string | number;
            /** Subtitlelabel */
            subtitleLabel?: string | null;
            /** Subtitlevalue */
            subtitleValue?: string | number | null;
            /** Tone */
            tone: string;
            /** Icon */
            icon: string;
        };
        /** DealCancelRequest */
        DealCancelRequest: {
            /** Comment */
            comment?: string | null;
        };
        /** DealCreateRequest */
        DealCreateRequest: {
            dealType: components["schemas"]["DealType"];
            /** City */
            city: string;
            /** Clientid */
            clientId?: number | null;
            /** Counterpartyid */
            counterpartyId?: number | null;
            /** Comment */
            comment?: string | null;
            /** Tronscanurl */
            tronscanUrl?: string | null;
            /** Body */
            body?: {
                [key: string]: unknown;
            };
            /** Profitrub */
            profitRub?: number | string | null;
            /** Dealat */
            dealAt?: string | null;
            /** Exchangeclientreqid */
            exchangeClientReqId?: string | null;
        };
        /** DealDetailsResponse */
        DealDetailsResponse: {
            deal: components["schemas"]["DealItemDto"];
            /** Dealno */
            dealNo: string;
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
            /** Dealat */
            dealAt?: string | null;
            /** Source */
            source: string;
            /** Sourcekind */
            sourceKind?: string | null;
            /** Counterpartyname */
            counterpartyName?: string | null;
            /** Counterpartypercent */
            counterpartyPercent?: number | null;
            /** Profitrub */
            profitRub: number;
            /** Comment */
            comment?: string | null;
            /** Tronscanurl */
            tronscanUrl?: string | null;
            /** Paymentwatchid */
            paymentWatchId?: string | null;
            /** Paymentwatchstatus */
            paymentWatchStatus?: string | null;
            /** Body */
            body?: {
                [key: string]: unknown;
            };
            bestChange?: components["schemas"]["BestChangeDetailsDto"] | null;
            /** Legs */
            legs?: components["schemas"]["DealLegDto"][];
            /** Statusevents */
            statusEvents?: components["schemas"]["DealStatusEventDto"][];
        };
        /** DealItemDto */
        DealItemDto: {
            /** Id */
            id: string;
            /** Clientname */
            clientName: string;
            /** Clientshortname */
            clientShortName: string;
            /** Dealtype */
            dealType: string;
            /** Asset */
            asset: string;
            /** Direction */
            direction: string;
            /** Amountrub */
            amountRub: number;
            /** City */
            city: string;
            status: components["schemas"]["DealStatus"];
            /** Insufficientusdt */
            insufficientUsdt?: boolean | null;
            /** Updatedlabel */
            updatedLabel: string;
            /** Createdby */
            createdBy: string;
            /** Onkanban */
            onKanban: boolean;
            /** Allowednextstatuses */
            allowedNextStatuses?: components["schemas"]["DealStatus"][];
        };
        /** DealLegDto */
        DealLegDto: {
            /** Id */
            id: string;
            /** Direction */
            direction: string;
            /** Currency */
            currency: string;
            /** Amount */
            amount: number;
            /** Rate */
            rate?: number | null;
            /** Status */
            status: string;
        };
        /** DealSourceEditRequest */
        DealSourceEditRequest: {
            exchange?: components["schemas"]["ExchangeSourceEditRequest"] | null;
            cash?: components["schemas"]["CashSourceEditRequest"] | null;
        };
        /**
         * DealStatus
         * @enum {string}
         */
        DealStatus: "new" | "fixed" | "balance_check" | "awaiting_payment" | "in_delivery" | "ready_for_cash_settlement" | "done" | "canceled";
        /** DealStatusEventDto */
        DealStatusEventDto: {
            /** Id */
            id: string;
            oldStatus: components["schemas"]["DealStatus"] | null;
            newStatus: components["schemas"]["DealStatus"];
            /** Actorname */
            actorName: string;
            /** Createdat */
            createdAt: string;
            /** Comment */
            comment?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** DealStatusRequest */
        DealStatusRequest: {
            status: components["schemas"]["DealStatus"];
            /** Comment */
            comment?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** DealStatusSummaryDto */
        DealStatusSummaryDto: {
            status: components["schemas"]["DealStatus"];
            /** Count */
            count: number;
            /** Totalrub */
            totalRub: number | null;
        };
        /**
         * DealType
         * @enum {string}
         */
        DealType: "sale" | "purchase" | "deposit" | "withdrawal" | "delivery" | "transfer_city" | "conversion" | "yuan" | "invoice" | "profit" | "best_change";
        /** DealUpdateRequest */
        DealUpdateRequest: {
            /** City */
            city?: string | null;
            /** Clientid */
            clientId?: number | null;
            /** Counterpartyid */
            counterpartyId?: number | null;
            /** Comment */
            comment?: string | null;
            /** Tronscanurl */
            tronscanUrl?: string | null;
            /** Body */
            body?: {
                [key: string]: unknown;
            } | null;
            /** Profitrub */
            profitRub?: number | string | null;
            /** Dealat */
            dealAt?: string | null;
        };
        /** DealsPageResponse */
        DealsPageResponse: {
            /** Summaries */
            summaries: components["schemas"]["DealStatusSummaryDto"][];
            /** Cities */
            cities: string[];
            /** Deals */
            deals: components["schemas"]["DealItemDto"][];
        };
        /** DurationMetricResponse */
        DurationMetricResponse: {
            /** Count */
            count: number;
            /** Successes */
            successes: number;
            /** Errors */
            errors: number;
            /** Cancellations */
            cancellations: number;
            /** Total Seconds */
            total_seconds: number;
            /** Max Seconds */
            max_seconds: number;
            /** Last Seconds */
            last_seconds: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** ExchangeSourceEditRequest */
        ExchangeSourceEditRequest: {
            /** Operationid */
            operationId: number;
            /** Recvcode */
            recvCode: string;
            /** Recvamount */
            recvAmount: number | string;
            /** Paycode */
            payCode: string;
            /** Payamount */
            payAmount: number | string;
            /** Rate */
            rate: number | string;
            /** Note */
            note?: string | null;
        };
        /** FulfillmentCancelRequest */
        FulfillmentCancelRequest: {
            /** Reason */
            reason: string;
        };
        /** FulfillmentQueueItemResponse */
        FulfillmentQueueItemResponse: {
            /** Id */
            id: number;
            /** Dealid */
            dealId: number;
            /** Requestkind */
            requestKind: string;
            /** Qty */
            qty: string;
            /** Sequenceno */
            sequenceNo: number;
            /** Status */
            status: string;
            /** Createdby */
            createdBy: number | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Reorderedby */
            reorderedBy: number | null;
            /** Reorderedat */
            reorderedAt: string | null;
        };
        /** FulfillmentQueueResponse */
        FulfillmentQueueResponse: {
            /** Items */
            items: components["schemas"]["FulfillmentQueueItemResponse"][];
            /** Queuedqty */
            queuedQty: string;
            /** Usdtfact */
            usdtFact: string | null;
            /** Queueshortageqty */
            queueShortageQty: string | null;
            /** Onchainliquidqty */
            onchainLiquidQty: string | null;
        };
        /** FulfillmentReorderRequest */
        FulfillmentReorderRequest: {
            /** Beforeitemid */
            beforeItemId?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["ApiUser"];
        };
        /** ManualCashAccountDto */
        ManualCashAccountDto: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Balance */
            balance: string;
        };
        /** ManualCashMoveDto */
        ManualCashMoveDto: {
            /** Id */
            id: number;
            /** Accountcode */
            accountCode: string;
            /** Operation */
            operation: string;
            /** Amount */
            amount: string;
            /** Balanceafter */
            balanceAfter: string;
            /**
             * Effectiveat
             * Format: date
             */
            effectiveAt: string;
            /** Comment */
            comment: string;
            /** Actorname */
            actorName: string;
            /** Reversalofid */
            reversalOfId: number | null;
            /** Reversed */
            reversed: boolean;
        };
        /** ManualCashMoveRequest */
        ManualCashMoveRequest: {
            /**
             * Accountcode
             * @enum {string}
             */
            accountCode: "moscow_poets" | "moscow_bs";
            /**
             * Operation
             * @enum {string}
             */
            operation: "inflow" | "outflow";
            /** Amount */
            amount: number | string;
            /**
             * Effectiveat
             * Format: date
             */
            effectiveAt: string;
            /** Comment */
            comment: string;
            /** Idempotencykey */
            idempotencyKey: string;
        };
        /** ManualCashReversalRequest */
        ManualCashReversalRequest: {
            /** Comment */
            comment: string;
            /** Idempotencykey */
            idempotencyKey: string;
        };
        /** ManualCashSnapshotResponse */
        ManualCashSnapshotResponse: {
            /** Accounts */
            accounts: components["schemas"]["ManualCashAccountDto"][];
            /** Moves */
            moves: components["schemas"]["ManualCashMoveDto"][];
        };
        /** MetricsResponse */
        MetricsResponse: {
            /** Use Cases */
            use_cases: {
                [key: string]: components["schemas"]["DurationMetricResponse"];
            };
            /** Queues */
            queues: {
                [key: string]: number;
            };
        };
        /** SettlementReplacementRequest */
        SettlementReplacementRequest: {
            /** Requestid */
            requestId: string;
            /** Tablerequestid */
            tableRequestId: string;
            /** Recvcode */
            recvCode: string;
            /** Recvamount */
            recvAmount: number | string;
            /** Paycode */
            payCode: string;
            /** Payamount */
            payAmount: number | string;
            /** Rate */
            rate: number | string;
        };
        /**
         * SettlementResolution
         * @enum {string}
         */
        SettlementResolution: "accept_actual" | "amend_unposted" | "cancel_and_recreate";
        /** SettlementResolutionResponse */
        SettlementResolutionResponse: {
            /** Settlementid */
            settlementId: number;
            /** Dealid */
            dealId: number;
            /** Status */
            status: string;
            resolution: components["schemas"]["SettlementResolution"];
            /** Expected */
            expected: string;
            /** Actual */
            actual: string;
            /** Delta */
            delta: string;
        };
        /** SettlementReviewResolutionRequest */
        SettlementReviewResolutionRequest: {
            resolution: components["schemas"]["SettlementResolution"];
            /** Comment */
            comment?: string | null;
            replacement?: components["schemas"]["SettlementReplacementRequest"] | null;
        };
        /** TelegramLoginRequest */
        TelegramLoginRequest: {
            /** Id */
            id: number;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Username */
            username?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Auth Date */
            auth_date: number;
            /** Hash */
            hash: string;
        };
        /** TelegramOidcLoginRequest */
        TelegramOidcLoginRequest: {
            /** Code */
            code: string;
            /** Code Verifier */
            code_verifier: string;
            /** Redirect Uri */
            redirect_uri: string;
            /** Nonce */
            nonce: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "cashier" | "manager" | "accountant" | "owner" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    metrics_api_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
    login_with_telegram_api_v1_auth_telegram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_with_telegram_oidc_api_v1_auth_telegram_oidc_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramOidcLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiUser"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_clients_api_v1_clients_get: {
        parameters: {
            query?: {
                search?: string | null;
                group?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientsPageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_v1_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_transactions_api_v1_clients__client_id__transactions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                client_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientTransactionsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_balances_api_v1_balances_get: {
        parameters: {
            query?: {
                currency?: string | null;
                sign?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalancesSnapshotResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    dashboard_shadow_report_api_v1_dashboard_shadow_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardShadowReportDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_rates_api_v1_dashboard_rates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    snapshot_api_v1_dashboard_manual_cash_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualCashSnapshotResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_api_v1_dashboard_manual_cash_moves_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualCashMoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualCashMoveDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reverse_api_v1_dashboard_manual_cash_moves__move_id__reverse_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                move_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualCashReversalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualCashMoveDto"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deals_api_v1_deals_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["DealStatus"][] | null;
                city?: string | null;
                type?: components["schemas"]["DealType"] | null;
                client_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealsPageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_deal_api_v1_deals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealDetailsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deal_api_v1_deals__deal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealDetailsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_deal_api_v1_deals__deal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealDetailsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_deal_status_api_v1_deals__deal_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealDetailsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_settlement_review_api_v1_settlements__settlement_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                settlement_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettlementReviewResolutionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementResolutionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_deal_source_api_v1_deals__deal_id__source_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealSourceEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealDetailsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_deal_source_api_v1_deals__deal_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealDetailsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fulfillments_api_v1_fulfillments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FulfillmentQueueResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reorder_fulfillment_api_v1_fulfillments__item_id__reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FulfillmentReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FulfillmentQueueItemResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_fulfillment_api_v1_fulfillments__item_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FulfillmentCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FulfillmentQueueItemResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
